name: Build and push dev Docker image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-image.yml'
      - '.github/workflows/build-image-dev.yml'
      - 'Dockerfile'
      - 'api.py'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: github.repository == 'ZJUIntl-share/ZJUIntl-RSS'
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      tags: dev
